# Sử dụng Python 3.10 slim cho nhẹ
FROM python:3.10-slim-bullseye

# Cài đặt git (cần thiết nếu dbt project của bạn có packages)
RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Cài đặt dbt-athena
# Lưu ý: dbt-athena-community sẽ tự động cài dbt-core tương ứng
RUN pip install --no-cache-dir dbt-athena-community==1.7.1

# Thiết lập thư mục làm việc mặc định
WORKDIR /dbt