# dbt_project.yml
name: 'restaurant_project'
version: '1.0.0'
config-version: 2
profile: 'restaurant_analytics'

models:
  restaurant_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
      +engine: 'ReplacingMergeTree()' 
      +order_by: ['report_date', 'order_id']
      +settings:
        allow_nullable_key: 1