name: 'restaurant_analytics'
version: '1.0.0'
profile: 'restaurant_snowflake'
model-paths: ["models"]

models:
  restaurant_analytics:
    staging:
      +materialized: view
      +schema: SILVER
    marts:
      +materialized: table
      +schema: GOLD
