restaurant_analytics: # Khớp với dbt_project.yml
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse-lab
      port: 8123
      user: admin
      password: password
      schema: restaurant_db
      secure: False
      verify: False