restaurant_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 8
      account: xlibfys-fwb58805
      user: tuanle
      password: Lethanhtuan97@!
      role: DE_ROLE
      database: RESTAURANT_DB
      warehouse: RESTAURANT_ETL_WH
      schema: BRONZE