version: 2

sources:
  - name: cukcuk
    schema: restaurant_db
    tables:
      - name: invoice_header
      - name: invoice_detail
      - name: customer
      - name: product
      - name: invoice_payment
      - name: order_header
      - name: order_detail
